# Generated by Django 4.2.23 on 2025-07-29 12:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='电话')),
                ('birth_date', models.DateField(blank=True, null=True, verbose_name='出生日期')),
                ('preferences', models.TextField(blank=True, verbose_name='旅行偏好')),
                ('avatar', models.URLField(blank=True, verbose_name='头像')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '用户资料',
                'verbose_name_plural': '用户资料',
            },
        ),
        migrations.CreateModel(
            name='TravelPreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('preferred_activities', models.TextField(blank=True, verbose_name='偏好的活动类型')),
                ('budget_range_min', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='预算范围最小值')),
                ('budget_range_max', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='预算范围最大值')),
                ('preferred_climate', models.CharField(blank=True, max_length=100, verbose_name='偏好的气候')),
                ('special_requirements', models.TextField(blank=True, verbose_name='特殊要求')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='travel_preference', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '旅行偏好',
                'verbose_name_plural': '旅行偏好',
            },
        ),
        migrations.CreateModel(
            name='TravelPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='计划标题')),
                ('description', models.TextField(blank=True, verbose_name='计划描述')),
                ('start_date', models.DateField(verbose_name='开始日期')),
                ('end_date', models.DateField(verbose_name='结束日期')),
                ('budget', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='预算')),
                ('destination', models.CharField(max_length=200, verbose_name='目的地')),
                ('is_public', models.BooleanField(default=False, verbose_name='是否公开')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='travel_plans', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '旅行计划',
                'verbose_name_plural': '旅行计划',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TravelItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='项目名称')),
                ('item_type', models.CharField(choices=[('luggage', '行李'), ('document', '证件'), ('other', '其他')], default='other', max_length=20, verbose_name='项目类型')),
                ('quantity', models.PositiveIntegerField(default=1, verbose_name='数量')),
                ('is_packed', models.BooleanField(default=False, verbose_name='是否已打包')),
                ('notes', models.TextField(blank=True, verbose_name='备注')),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='travel_items', to='travel.travelplan')),
            ],
            options={
                'verbose_name': '旅行清单项目',
                'verbose_name_plural': '旅行清单项目',
            },
        ),
        migrations.CreateModel(
            name='Itinerary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='行程标题')),
                ('description', models.TextField(blank=True, verbose_name='行程描述')),
                ('date', models.DateField(verbose_name='日期')),
                ('start_time', models.TimeField(verbose_name='开始时间')),
                ('end_time', models.TimeField(verbose_name='结束时间')),
                ('location', models.CharField(blank=True, max_length=200, verbose_name='地点')),
                ('notes', models.TextField(blank=True, verbose_name='备注')),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itineraries', to='travel.travelplan')),
            ],
            options={
                'verbose_name': '行程安排',
                'verbose_name_plural': '行程安排',
                'ordering': ['date', 'start_time'],
            },
        ),
        migrations.CreateModel(
            name='Destination',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='目的地名称')),
                ('description', models.TextField(blank=True, verbose_name='描述')),
                ('arrival_date', models.DateField(verbose_name='到达日期')),
                ('departure_date', models.DateField(verbose_name='离开日期')),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='纬度')),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='经度')),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='destinations', to='travel.travelplan')),
            ],
            options={
                'verbose_name': '目的地',
                'verbose_name_plural': '目的地',
            },
        ),
        migrations.CreateModel(
            name='Attraction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='景点名称')),
                ('description', models.TextField(blank=True, verbose_name='描述')),
                ('visit_time', models.DateTimeField(verbose_name='参观时间')),
                ('duration', models.PositiveIntegerField(default=60, verbose_name='预计时长(分钟)')),
                ('cost', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='费用')),
                ('address', models.CharField(blank=True, max_length=300, verbose_name='地址')),
                ('destination', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attractions', to='travel.destination')),
            ],
            options={
                'verbose_name': '景点',
                'verbose_name_plural': '景点',
            },
        ),
    ]
